### ISSUE TITLE
Gulp is broken.

### ISSUE THREAD

**Issue by jacquestardie** [jacquestardie/learning-journal#14]
Dat CSS isn't building appropriately.

```
module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/node_modules/gulp/node_modules/v8flags/cache/3.28.73.flags.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:25:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

Sigh.

**Comment by jacquestardie** [comment]
Closed with 08de3904d

Gulp at `3.8.9` introduced a bug with `v8flags`, so rolling back to `3.8.8`.

**Comment by ohEmily** [comment]
I'm getting this same error, but rolling back to 3.8.8 didn't fix it. Do you happen to have any other ideas?

**Comment by jacquestardie** [comment]
@ohEmily I'm a little foggy, but there's some about v8flags and the npm cache that was causing some errors. I think I ended up [clearing my npm cache](https://docs.npmjs.com/cli/cache), which someone else had pointed out might be an issue.
